### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by kiwindyy** [hoodiexxx/lol_player_KDA_prediction#1]
Peer Review Conducted: November 26, 2024 at 3:00pm

## Summary
This paper uses a combination of methods to predict the Kill-Death-Assist (KDA) ratio of players on BLG in the 2024 LoL Pro League season. It analyzes in-game metrics such as gold earned, vision score, and damage to champions. The study applies different modeling techniques, including simple LR, multiple LR, and Bayesian modeling. The goal is to assess player performance, highlight top players, and provide guidance for team management decisions.

## Strong Positive Points
* The paper uses multiple types of models to thoroughly analyze the data, giving a clear view of player performance
* Mathematical calculations are explained, making the methods easy to follow for readers who may not be familiar with the topic
* The measurement section is well-organized, helping readers understand how the data was collected and prepared
* Each model is explained clearly, with detailed breakdowns that help readers understand the methods and results

## Critical Improvement
1. Provide explanations for specific league terms that might be unfamiliar to some readers. For example, describe "creep score" and explain its role in generating gold, which allows players to buy items that improve their performance and influence the game.
2. Adjust the tables and figures to make them easier to read, removing overlapping values and ensuring the axis labels are clear and legible.
3. Finish the incomplete sections, including model justification, results, discussion, and appendix, to make sure the paper is complete.

## Suggestions for Improvement
* Clearly explain how the findings can be applied to team decisions, such as choosing roster changes or refining drafting strategies.
* Expand the introduction to include more details that help readers unfamiliar with League of Legends understand the context.
* Use consistent and distinct colour coding for team members in all graphs to avoid confusion and improve clarity.
* Consider relocating the posterior predictive check to the appendix to keep the main body of the paper more focused.
* Remove any unused files and update the README to reflect the content and purpose of your study.
* Ensure the title and abstract directly address the findings from your research to better represent the study’s contributions.

## Evaluation
R is appropriately cited: 1/1
Data are appropriately cited: 1/1
Class paper: 1/1
LLM usage is documented: 1/1
Title: 1/2
Author, date, and repo: 2/2
Abstract: 2/4
Introduction: 3/4
Estimand: 1/1
Data: 8/10
Measurement: 3/4
Model: 8/10
Results: 0/10
Discussion: 0/10
Prose: 4/6
Cross-references: 0/1
Captions: 2/2
Graphs/tables/etc: 2/4
Surveys, sampling, and observational data: 0/10
Referencing: 4/4
Commits: 2/2
Sketches: 2/2
Simulation: 3/4
Tests: 3/4
Parquet: 1/1
Reproducible workflow: 3/4
Enhancements: 2/4
Miscellaneous: 1/3

## Estimated Overall Mark
62 out of 112

## Any Other Comments
This paper focuses on an important and growing area in esports analytics with strong potential for practical use. Improving the results and discussion sections and including more detailed model checks will make the research clearer and more useful.

**Comment by hoodiexxx** [comment]
just add Result section, model section, Surveys, sampling, and observational data section in the new commit and add explaination about total creep.   thanks for your review.
