### ISSUE TITLE
Peer Review #3

### ISSUE THREAD

**Issue by Wang20030509** [hoodiexxx/lol_player_KDA_prediction#3]
### Summary
This paper presents a hybrid model to forecast the Kill-Death-Assist (KDA) ratios of players on the Bilibili Gaming (BLG) team in the League of Legends Pro League (LPL). The model incorporates both traditional metrics (e.g., vision score, total creep score, gold earned) and advanced Bayesian methods to deliver performance predictions and insights for strategic decision-making.

### Strong positive points:

- The topic is highly engaging and directly relevant to the growing field of esports analytics.

- The choice of KDA as the primary metric is insightful; it balances comprehensibility and strategic importance, as it resonates with fans and decision-makers alike.

- The comprehensive approach to data cleaning and modeling, including simple, multiple, and Bayesian regression, showcases methodological rigor.

### Critical improvements needed:

- The discussion on limitations, particularly concerning the potential biases in data and predictors, needs further elaboration. For example, the impact of game meta changes on predictive accuracy is underexplored.

- The model could include additional predictors such as player synergy, champion diversity, or patch-specific effects to enhance predictive robustness.

- The Bayesian model exhibits strong results, but its underperformance on extreme values needs clearer explanations and potential mitigation strategies (e.g., incorporating non-linear interactions).

- While the paper discusses random effects (e.g., position, side), their interpretation in influencing player KDA is insufficiently detailed.

### Suggestions for Improvement:

- Consider adding visualizations that compare the actual and predicted values across all three models (SLR, MLR, Bayesian) for easier cross-model comparison.

- Expand the discussion on the ethical implications of performance metrics in esports, particularly regarding contract decisions and public perception of players.

- Incorporate a sensitivity analysis to determine the influence of key predictors like vision score and gold earned on the model’s outcomes.

- Clarify the rationale for choosing specific metrics, such as total CS, over alternatives like damage share or crowd control score.

- Address the potential impact of regional playstyle differences on the dataset’s generalizability (e.g., how the aggressive LPL style may bias predictions for slower leagues).

### Evaluation:
Rubric Marks
R/Python cited (1/1): Clear citations for tools used in both R and Python.
Data cited (1/1): Oracle’s Elixir as the source is well-documented.
Class paper (1/1): Suitable for an academic audience.
LLM documentation (1/1): Adequate documentation for machine learning methods.
Title (2/2): Informative and specific.
Author, date, and repo (2/2): Clearly mentioned.
Abstract (4/4): Comprehensive and engaging.
Introduction (4/4): Effectively sets the context.
Estimand (1/1): Clearly defined as KDA.
Data (10/10): Well-documented and preprocessed.
Measurement (4/4): Accurate and standardized.
Model (9/10): Strong, but room for refinement in Bayesian modeling assumptions.
Results (9/10): Well-presented, though outliers could be better addressed.
Discussion (9/10): Insightful but could explore broader implications more deeply.
Prose (6/6): Clear and professional.
Cross-references (1/1): Well-connected sections.
Captions (2/2): Descriptive and concise.
Graphs/tables/etc (4/4): Effective and informative.
Surveys, sampling, and observational data appendix (9/10): Thorough but slightly redundant.
Referencing (3/4): There are still useless references in .bib file
Commits (2/2): Clearly mentioned.
Sketches (2/2): Relevant details included.
Simulation (4/4): Rigorous and well-explained.
Tests (4/4): Robust validation methods.
Parquet (1/1): File format well-utilized.
Reproducible workflow (4/4): Excellent reproducibility.
Enhancements (3/4): Could benefit from interaction effects.
Miscellaneous (3/3): Covers a range of related topics effectively.
Estimated overall mark:
94 out of 100.

### Other comments:
The theme of this paper is highly appealing, particularly for fans and stakeholders in esports analytics. I found the focus on KDA both practical and engaging, especially given its significance as a predictive and evaluative metric in competitive gaming.

**Comment by hoodiexxx** [comment]
just add explanation about model performance in the extreme value and the limitation part in the new commits, thanks for your review.
