### ISSUE TITLE
Peer review #4

### ISSUE THREAD

**Issue by xgao28** [hoodiexxx/lol_player_KDA_prediction#4]
### Summary

The paper applies a Bayesian model to predict **KDA** (Kill/Death/Assist ratio), a performance metric for professional *League of Legends* players on the BLG team, using predictor variables such as **vision score**, **total gold**, and **damage to champions**. It compares this Bayesian approach against other models, providing analyses that justify its selection over alternatives. The paper also includes a dataset-specific discussion to contextualize the findings.

---

### Strengths

- **Visual Presentation:** *Figure 1* stands out as exceptional in clarity and design.  
- **Methodology:** Effective use of multiple models for comparison, ensuring the Bayesian model is chosen with evidence and explanation, rather than arbitrarily.  
- **Comprehensive Graphs:** Multiple visualizations (e.g., residuals, credible intervals) enrich the analysis, highlighting key aspects of the models.  

---

### Critical Improvements

- **Predictive Factors:** Provide rationale for modeling **total gold** and **total CS** as linear predictors while treating **position** as a random normal distribution.  
- **Terminology:** Section 2.4.1 introduces terms like *top lane*, *Renekton*, and *utility champions* without adequate explanation or references. These terms should be defined for clarity, especially for readers less familiar with esports.  
- **Relevance of Insights:** Section 2.4.1 feels disconnected from the rest of the paper as the insights there aren’t integrated elsewhere. Either tie these insights back to the main analysis or relocate them to the appendix.   
- **Graph Design:** The graphs lack cohesive styling—colors (e.g., blues in Figures 2 and 4) appear inconsistent. Harmonizing color schemes across all figures will improve visual coherence.  
- **Clarity in Table 0:** It is not evident enough that displaying all 52 column header is necessary. 
- **Cross references:** some of the cross references are not rendered in the paper.

---

### Suggestions for Improvement  

- **Abstract and Introduction:** Include results and insights from the model to provide a complete overview.  
- **Discussion:** Add quantifiable details where relevant (e.g., how Bin’s contract or in-game priority impacts his performance). Reframe the placement of player-specific insights into the discussion section for better alignment with findings.  

- **Data Section:** Relocate extraneous variables and discussions to the appendix for conciseness.  
- **Graphs and Captions:** Improve figure captions by providing sufficient context upfront (e.g., Bin’s “superstar” status).  
- Ensure unnecessary files (like `renv`) are excluded from the workflow.  

---

### Evaluation  

R/Python cited (1/1)
Data cited (1/1)
Class paper (1/1)
LLM documentation (1/1)
Title (1/2) results needs to be displayed.
Author, date, and repo (2/2)
Abstract (3/4) results and insights
Introduction (3/4)
Same as above, other parts of the introduction are really strong though.
Estimand (1/1)
Present.
Data (7/10)
Variables of interest are introduced, but so are variables that are not of interest.
Measurement (4/4)
Model (6/10)
Good
Results (7/10)
Good results section, but the insights on Bin following up from the data on him from the model is better left in the discussion section rather than here.
Discussion (6/10)
Interesting read, but lacks a bit of context in section 5.2. How much of a higher contract does Bin have than Elk, for example? I also don't have much knowledge on how in-game priority or Bin's negative impact on team performance are really quantified or understood.
Prose (2/6)
The way the text is written contains multiple minor flaws.
Cross-references (0/1)
Present in the code but somehow it is not rendered.
Captions (1/2)
Some tables does not have a caption.
Graphs/tables/etc (2/4)
The text for Figure 1, especially for the x-axis, is not observable.
Surveys, sampling, and observational data appendix (6/10)
Be more specific about what the survey is for would be preferred.
Referencing (4/4)
Commits (2/2)
Sketches (2/2)
Simulation (3/4)
Tests (3/4)
Parquet (1/1)
Reproducible workflow (3/4)
replication.R is not used but present in the repo.
Enhancements (2/4)
Miscellaneous (2/3)
Interesting choice of topic.
Estimated overall mark:
81 out of 112.

---

### Final Remarks  

The paper is a solid, well-researched piece with strong visuals and compelling insights. By addressing the clarity, cohesion, and minor inconsistencies in both analysis and presentation, it has the potential to reach an even higher standard.

**Comment by hoodiexxx** [comment]
Thank you for the detailed feedback! All issues have been addressed, including adding quantifiable results to the abstract and introduction, providing rationale for predictors, and defining esports-specific terms for clarity. Player-specific insights, such as Bin's performance and contract value, have been moved to the discussion section and reframed with quantifiable context. Graph designs were harmonized, captions improved, and cross-references fixed to ensure proper rendering. Unnecessary columns were omitted from tables, and font sizes adjusted for readability. The prose was revised to improve clarity and remove minor errors. The survey section was enhanced with clear sampling and implementation details, and the reproducible workflow was streamlined by removing irrelevant files like `replication.R`.
