### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Chendong-Fei** [hoodiexxx/lol_player_KDA_prediction#5]
**Summary**
This paper presents a hybrid model for forecasting the Kill-Death-Assist (KDA) ratios of players from the Bilibili Gaming (BLG) team in the League of Legends Pro League (LPL). By utilizing in-game metrics and advanced statistics such as total creep score, the paper integrates machine learning models, including Bayesian hierarchical models, to analyze player performance. The study provides actionable insights for optimizing team strategies and evaluating player contracts.

**Strong Positive Points**

- The hybrid modeling approach effectively combines traditional and advanced statistical metrics for comprehensive performance forecasting.
- Clear implications for practical esports applications, offering actionable insights for management and strategy.

**Critical Improvements Needed**

- Addressing Model Limitations: The manuscript highlights that the KDA metric may overlook intangible contributions like leadership or adaptability. To strengthen credibility, the authors should provide strategies to address these gaps.
- Data Variability: The inclusion of multiple leagues with differing playstyles introduces potential biases. The authors should either adjust for these biases or clarify their implications for model generalizability.

**Suggestions for Improvement**

- Expand on Data Limitations: Clearly outline how differing metas across leagues were accounted for and discuss implications for cross-regional generalization.
- Visual Refinements: Enhance the clarity of figures, such as Figure 4, by adding titles, consistent labeling, and annotations to highlight key trends.
- Grammar and Formatting: Address minor typos (e.g., "this paper developing" in Section 1) and maintain consistent formatting, particularly in tables and plots.

Evaluation
R is appropriately cited: 1/1
Data are appropriately cited: 1/1
Class paper: 1/1
LLM usage is documented: 1/1
Title: 1/2
Author, date, and repo: 2/2
Abstract: 2/4
Introduction: 3/4
Estimand: 1/1
Data: 8/10
Measurement: 3/4
Model: 8/10
Results: 8/10
Discussion: 8/10
Prose: 4/6
Cross-references: 1/1
Captions: 2/2
Graphs/tables/etc: 3/4
Surveys, sampling, and observational data: 6/10
Referencing: 4/4
Commits: 2/2
Sketches: 2/2
Simulation: 3/4
Tests: 4/4
Parquet: 1/1
Reproducible workflow: 3/4
Enhancements: 4/4
Miscellaneous: 2/3

**Estimated Overall Mark**
90 out of 112

**Any Other Comments**
The manuscript demonstrates strong analytical rigor and practical implications.

**Comment by hoodiexxx** [comment]
just add the part regarding model limitation, thanks for your review.
